from __future__ import annotations

import json
from pathlib import Path
from typing import Any
import uuid

from zddv.config import ProjectConfig, save_project
from zddv.storage import get_run_record
from zddv.uvm_item import analyze_uvm_item_file


INSTRUMENTATION_PREFIX = "ZDDV_ITEM_TRACE_V1|"
_FIELDS = (
    "event",
    "item_id",
    "sequence_id",
    "sequence",
    "sequencer",
    "item",
    "transaction_id",
    "time",
)

_SV_PACKAGE = """// Generated by ZDDV. Portable sequence-item trace helper.
package zddv_uvm_item_trace_pkg;
  localparam string ZDDV_UVM_ITEM_PREFIX = "ZDDV_ITEM_TRACE_V1";

  function automatic string zddv_clean(input string value);
    string result;
    result = value;
    for (int i = 0; i < result.len(); i++) begin
      byte ch;
      ch = result.getc(i);
      if ((ch == 8'h7c) || (ch == 8'h0a) || (ch == 8'h0d))
        result.putc(i, 8'h5f);
    end
    return result;
  endfunction

  function automatic string zddv_optional(input string value);
    if (value.len() == 0)
      return "-";
    return zddv_clean(value);
  endfunction

  task automatic zddv_uvm_item_emit(
    input string event_name,
    input string item_id,
    input string sequence_id,
    input string sequence_name,
    input string sequencer_name,
    input string item_name,
    input longint transaction_id
  );
    string transaction_text;
    if (transaction_id < 0)
      transaction_text = "-";
    else
      transaction_text = $sformatf("%0d", transaction_id);

    $display(
      "ZDDV_ITEM_TRACE_V1|%s|%s|%s|%s|%s|%s|%s|%0t",
      zddv_clean(event_name),
      zddv_clean(item_id),
      zddv_optional(sequence_id),
      zddv_optional(sequence_name),
      zddv_optional(sequencer_name),
      zddv_optional(item_name),
      transaction_text,
      $time
    );
  endtask
endpackage

`define ZDDV_UVM_ITEM_EMIT(EVENT_NAME, ITEM_ID, SEQUENCE_ID, SEQUENCE_NAME, SEQUENCER_NAME, ITEM_NAME, TRANSACTION_ID) \
  zddv_uvm_item_trace_pkg::zddv_uvm_item_emit(EVENT_NAME, ITEM_ID, SEQUENCE_ID, SEQUENCE_NAME, SEQUENCER_NAME, ITEM_NAME, TRANSACTION_ID)

`define ZDDV_UVM_ITEM_GRANT(ITEM_ID, SEQUENCE_ID, SEQUENCE_NAME, SEQUENCER_NAME, ITEM_NAME, TRANSACTION_ID) \
  `ZDDV_UVM_ITEM_EMIT("GRANT", ITEM_ID, SEQUENCE_ID, SEQUENCE_NAME, SEQUENCER_NAME, ITEM_NAME, TRANSACTION_ID)

`define ZDDV_UVM_ITEM_REQUEST(ITEM_ID, SEQUENCE_ID, SEQUENCE_NAME, SEQUENCER_NAME, ITEM_NAME, TRANSACTION_ID) \
  `ZDDV_UVM_ITEM_EMIT("REQUEST", ITEM_ID, SEQUENCE_ID, SEQUENCE_NAME, SEQUENCER_NAME, ITEM_NAME, TRANSACTION_ID)

`define ZDDV_UVM_ITEM_DONE(ITEM_ID, SEQUENCE_ID, SEQUENCE_NAME, SEQUENCER_NAME, ITEM_NAME, TRANSACTION_ID) \
  `ZDDV_UVM_ITEM_EMIT("ITEM_DONE", ITEM_ID, SEQUENCE_ID, SEQUENCE_NAME, SEQUENCER_NAME, ITEM_NAME, TRANSACTION_ID)

`define ZDDV_UVM_ITEM_RESPONSE(ITEM_ID, SEQUENCE_ID, SEQUENCE_NAME, SEQUENCER_NAME, ITEM_NAME, TRANSACTION_ID) \
  `ZDDV_UVM_ITEM_EMIT("RESPONSE", ITEM_ID, SEQUENCE_ID, SEQUENCE_NAME, SEQUENCER_NAME, ITEM_NAME, TRANSACTION_ID)
"""


def _optional_field(value: str) -> str | None:
    normalized = value.strip()
    return None if normalized in {"", "-"} else normalized


def parse_uvm_item_instrumentation_log(
    text: str,
    *,
    source: str = "zddv-uvm-item-instrumentation",
) -> dict[str, Any]:
    events: list[dict[str, Any]] = []
    for line_number, line in enumerate(text.splitlines(), start=1):
        marker = line.find(INSTRUMENTATION_PREFIX)
        if marker < 0:
            continue

        encoded = line[marker + len(INSTRUMENTATION_PREFIX) :]
        fields = encoded.split("|")
        if len(fields) != len(_FIELDS):
            raise ValueError(
                f"Malformed ZDDV UVM item record at log line {line_number}: "
                f"expected {len(_FIELDS)} fields, got {len(fields)}"
            )

        record = dict(zip(_FIELDS, fields, strict=True))
        event_name = record["event"].strip().upper()
        item_id = record["item_id"].strip()
        if not event_name or event_name == "-":
            raise ValueError(
                f"Malformed ZDDV UVM item record at log line {line_number}: "
                "event is required"
            )
        if not item_id or item_id == "-":
            raise ValueError(
                f"Malformed ZDDV UVM item record at log line {line_number}: "
                "item_id is required"
            )

        events.append(
            {
                "event": event_name,
                "item_id": item_id,
                "sequence_id": _optional_field(record["sequence_id"]),
                "sequence": _optional_field(record["sequence"]),
                "sequencer": _optional_field(record["sequencer"]),
                "item": _optional_field(record["item"]),
                "transaction_id": _optional_field(record["transaction_id"]),
                "time": _optional_field(record["time"]),
                "metadata": {
                    "instrumentation": "ZDDV_ITEM_TRACE_V1",
                    "log_line": line_number,
                },
            }
        )

    if not events:
        raise ValueError("No ZDDV UVM item instrumentation records found in log")

    return {"source": source, "events": events}


def _resolve_log_path(
    project: ProjectConfig,
    path: str | Path | None,
    run_id: str | None,
) -> Path:
    if path is None:
        if run_id is None:
            raise ValueError("A log path or --run is required")
        run = get_run_record(project, run_id)
        if run is None:
            raise ValueError(f"Unknown run ID: {run_id}")
        selected = Path(run["log"])
    else:
        selected = Path(path)
        if not selected.is_absolute():
            selected = project.root / selected

    selected = selected.resolve()
    if not selected.is_file():
        raise FileNotFoundError(selected)
    return selected


def extract_uvm_item_instrumentation_log(
    project: ProjectConfig,
    path: str | Path | None = None,
    *,
    run_id: str | None = None,
    source: str = "zddv-uvm-item-instrumentation",
    output: str | Path | None = None,
) -> Path:
    log_path = _resolve_log_path(project, path, run_id)
    payload = parse_uvm_item_instrumentation_log(
        log_path.read_text(encoding="utf-8", errors="replace"),
        source=source,
    )

    if output is None:
        label = run_id or f"manual-{uuid.uuid4().hex[:8]}"
        destination = (
            project.root
            / ".zddv"
            / "uvm"
            / "items"
            / "instrumented"
            / f"{label}.json"
        )
    else:
        destination = Path(output)
        if not destination.is_absolute():
            destination = project.root / destination

    destination = destination.resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return destination


def analyze_uvm_item_instrumentation_log(
    project: ProjectConfig,
    path: str | Path | None = None,
    *,
    run_id: str | None = None,
    source: str = "zddv-uvm-item-instrumentation",
    output: str | Path = ".zddv/uvm/items/latest.json",
) -> dict[str, Any]:
    trace_path = extract_uvm_item_instrumentation_log(
        project,
        path,
        run_id=run_id,
        source=source,
    )
    return analyze_uvm_item_file(
        project,
        trace_path,
        source=source,
        output=output,
        run_id=run_id,
    )


def analyze_uvm_item_instrumentation_log_if_present(
    project: ProjectConfig,
    path: str | Path,
    *,
    run_id: str,
    source: str,
) -> dict[str, Any] | None:
    log_path = _resolve_log_path(project, path, run_id)
    text = log_path.read_text(encoding="utf-8", errors="replace")
    if INSTRUMENTATION_PREFIX not in text:
        return None
    return analyze_uvm_item_instrumentation_log(
        project,
        log_path,
        run_id=run_id,
        source=source,
    )


def write_uvm_item_instrumentation(
    project: ProjectConfig,
    *,
    output: str | Path = "tb/zddv_uvm_item_trace_pkg.sv",
    add_source: bool = True,
    force: bool = False,
) -> dict[str, Any]:
    destination = Path(output)
    if not destination.is_absolute():
        destination = project.root / destination
    destination = destination.resolve()

    if destination.exists() and not force:
        raise FileExistsError(
            f"{destination} already exists; pass --force to replace it"
        )

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(_SV_PACKAGE, encoding="utf-8")

    added = False
    project_path: str | None = None
    if add_source:
        try:
            project_path = destination.relative_to(project.root.resolve()).as_posix()
        except ValueError as exc:
            raise ValueError(
                "Instrumentation must be inside the project when --add-source is used"
            ) from exc
        if project_path not in project.tb:
            project.tb.insert(0, project_path)
            save_project(project)
            added = True

    return {
        "path": str(destination),
        "project_path": project_path,
        "added_to_project": added,
        "format": "ZDDV_ITEM_TRACE_V1",
    }
