from __future__ import annotations

from pathlib import Path
from typing import Any

from zddv.config import ProjectConfig, save_project
from zddv.uvm_item_instrumentation import (
    DEFAULT_UVM_ITEM_HELPER,
    write_uvm_item_instrumentation,
)
from zddv.uvm_sequence_instrumentation import (
    DEFAULT_UVM_SEQUENCE_HELPER,
    write_uvm_sequence_instrumentation,
)


DEFAULT_UVM_AUTO_ADAPTER = "tb/zddv_uvm_auto_trace_pkg.sv"

_SV_PACKAGE = r'''// Generated by ZDDV. Opt-in UVM 1800.2 sequence/item trace adapter.
//
// Adoption contract:
//   1. Extend zddv_instrumented_sequence #(REQ, RSP).
//   2. Implement zddv_body() instead of overriding body().
//   3. Use inherited start_item()/finish_item()/get_response() for automatic markers.
//
// This adapter uses public virtual UVM sequence APIs. It does not patch uvm_pkg,
// inspect hidden sequencer queues, infer arbitration policy, or execute tests.
package zddv_uvm_auto_trace_pkg;

  import uvm_pkg::*;
  import zddv_uvm_sequence_trace_pkg::*;
  import zddv_uvm_item_trace_pkg::*;

  virtual class zddv_instrumented_sequence #(
    type REQ = uvm_sequence_item,
    type RSP = REQ
  ) extends uvm_sequence #(REQ, RSP);

    static longint unsigned zddv_execution_serial = 0;

    protected string zddv_trace_id;
    protected string zddv_trace_sequencer;
    protected string zddv_item_by_transaction[int];

    function new(string name = "zddv_instrumented_sequence");
      super.new(name);
      zddv_trace_id = "";
      zddv_trace_sequencer = "";
    endfunction

    protected function string zddv_sequence_label();
      string label;
      label = get_type_name();
      if (label.len() == 0)
        label = get_name();
      return label;
    endfunction

    protected function string zddv_sequencer_label(
      uvm_sequencer_base candidate = null
    );
      uvm_sequencer_base selected;
      selected = candidate;
      if (selected == null)
        selected = get_sequencer();
      if (selected == null)
        return "";
      return selected.get_full_name();
    endfunction

    protected function string zddv_item_trace_id(uvm_sequence_item item);
      if (item == null)
        return "";
      return $sformatf("%s/item@%0d", zddv_trace_id, item.get_inst_id());
    endfunction

    protected task zddv_emit_sequence_state(input string state_name);
      zddv_uvm_sequence_trace_pkg::zddv_uvm_sequence_emit(
        state_name,
        zddv_trace_id,
        zddv_sequence_label(),
        zddv_trace_sequencer,
        ""
      );
    endtask

    protected task zddv_emit_item_event(
      input string event_name,
      input uvm_sequence_item item,
      input uvm_sequencer_base sequencer = null,
      input string forced_item_id = ""
    );
      string item_id;
      string sequencer_name;
      longint transaction_id;

      if (item == null)
        return;

      item_id = forced_item_id;
      if (item_id.len() == 0)
        item_id = zddv_item_trace_id(item);

      sequencer_name = zddv_sequencer_label(sequencer);
      transaction_id = item.get_transaction_id();

      zddv_uvm_item_trace_pkg::zddv_uvm_item_emit(
        event_name,
        item_id,
        zddv_trace_id,
        zddv_sequence_label(),
        sequencer_name,
        item.get_type_name(),
        transaction_id
      );
    endtask

    // UVM 1800.2-2020 14.2.3.1. A new ZDDV execution identity is
    // allocated per start(), avoiding the internal/private-use sequence_id API.
    virtual task start(
      uvm_sequencer_base sequencer,
      uvm_sequence_base parent_sequence = null,
      int this_priority = -1,
      bit call_pre_post = 1
    );
      zddv_execution_serial = zddv_execution_serial + 1;
      zddv_trace_id = $sformatf(
        "uvm-object-%0d-run-%0d",
        get_inst_id(),
        zddv_execution_serial
      );
      zddv_trace_sequencer = zddv_sequencer_label(sequencer);
      zddv_item_by_transaction.delete();

      zddv_emit_sequence_state("UVM_CREATED");
      super.start(sequencer, parent_sequence, this_priority, call_pre_post);

      if (get_sequence_state() == UVM_STOPPED)
        zddv_emit_sequence_state("UVM_STOPPED");
      else if (get_sequence_state() == UVM_FINISHED)
        zddv_emit_sequence_state("UVM_FINISHED");
    endtask

    virtual task pre_start();
      zddv_emit_sequence_state("UVM_PRE_START");
      super.pre_start();
    endtask

    virtual task pre_body();
      zddv_emit_sequence_state("UVM_PRE_BODY");
      super.pre_body();
    endtask

    // Derived ZDDV-instrumented sequences implement this hook instead of
    // overriding body(), so the BODY/ENDED evidence cannot be skipped.
    pure virtual task zddv_body();

    virtual task body();
      zddv_emit_sequence_state("UVM_BODY");
      zddv_body();
      zddv_emit_sequence_state("UVM_ENDED");
    endtask

    virtual task post_body();
      zddv_emit_sequence_state("UVM_POST_BODY");
      super.post_body();
    endtask

    virtual task post_start();
      zddv_emit_sequence_state("UVM_POST_START");
      super.post_start();
    endtask

    // UVM 1800.2-2020 14.2.6.2. ARB_REQUEST is emitted immediately before
    // the standard call; GRANT is emitted only after start_item() returns.
    virtual task start_item(
      uvm_sequence_item item,
      int set_priority = -1,
      uvm_sequencer_base sequencer = null
    );
      if (item != null)
        zddv_emit_item_event("ARB_REQUEST", item, sequencer);

      super.start_item(item, set_priority, sequencer);

      if (item != null)
        zddv_emit_item_event("GRANT", item, item.get_sequencer());
    endtask

    // UVM 1800.2-2020 14.2.6.3. finish_item() contains send_request()
    // and wait_for_item_done(); REQUEST therefore precedes the call and
    // ITEM_DONE is emitted only after the standard call returns.
    virtual task finish_item(
      uvm_sequence_item item,
      int set_priority = -1
    );
      string item_id;
      int transaction_id;

      if (item != null) begin
        item_id = zddv_item_trace_id(item);
        zddv_emit_item_event("REQUEST", item, item.get_sequencer(), item_id);
      end

      super.finish_item(item, set_priority);

      if (item != null) begin
        transaction_id = item.get_transaction_id();
        if (transaction_id >= 0)
          zddv_item_by_transaction[transaction_id] = item_id;
        zddv_emit_item_event("ITEM_DONE", item, item.get_sequencer(), item_id);
      end
    endtask

    // UVM 1800.2-2020 14.3.3.3. A response is linked back to the original
    // request when an explicit transaction_id matches one observed above.
    virtual task get_response(
      output RSP response,
      input int transaction_id = -1
    );
      string item_id;
      int observed_transaction_id;

      super.get_response(response, transaction_id);
      if (response != null) begin
        observed_transaction_id = response.get_transaction_id();
        if (
          (observed_transaction_id >= 0) &&
          zddv_item_by_transaction.exists(observed_transaction_id)
        )
          item_id = zddv_item_by_transaction[observed_transaction_id];
        else
          item_id = zddv_item_trace_id(response);

        zddv_emit_item_event(
          "RESPONSE",
          response,
          response.get_sequencer(),
          item_id
        );
      end
    endtask

  endclass

endpackage
'''


def _resolve_registered_path(
    project: ProjectConfig,
    output: str | Path,
    *,
    label: str,
) -> tuple[Path, str]:
    destination = Path(output)
    if not destination.is_absolute():
        destination = project.root / destination
    destination = destination.resolve()
    try:
        project_path = destination.relative_to(project.root.resolve()).as_posix()
    except ValueError as exc:
        raise ValueError(
            f"{label} must be inside the project when source registration is enabled"
        ) from exc
    return destination, project_path


def _ensure_helper(
    project: ProjectConfig,
    *,
    relative_path: str,
    writer,
    required_tokens: tuple[str, ...],
) -> tuple[Path, bool]:
    destination = (project.root / relative_path).resolve()
    if destination.exists():
        if not destination.is_file():
            raise ValueError(f"Expected instrumentation helper file: {destination}")
        text = destination.read_text(encoding="utf-8", errors="replace")
        missing = [token for token in required_tokens if token not in text]
        if missing:
            raise ValueError(
                f"Existing instrumentation helper {destination} is incompatible; "
                f"missing required API token(s): {', '.join(missing)}"
            )
        return destination, False

    writer(
        project,
        output=relative_path,
        add_source=False,
        force=False,
    )
    return destination, True


def write_uvm_auto_instrumentation(
    project: ProjectConfig,
    *,
    output: str | Path = DEFAULT_UVM_AUTO_ADAPTER,
    add_source: bool = True,
    force: bool = False,
) -> dict[str, Any]:
    """Generate an opt-in UVM base-sequence adapter using explicit marker helpers."""

    destination = Path(output)
    project_path: str | None = None
    if add_source:
        destination, project_path = _resolve_registered_path(
            project,
            output,
            label="UVM auto-instrumentation adapter",
        )
    else:
        if not destination.is_absolute():
            destination = project.root / destination
        destination = destination.resolve()

    reserved_helpers = {
        (project.root / DEFAULT_UVM_SEQUENCE_HELPER).resolve(),
        (project.root / DEFAULT_UVM_ITEM_HELPER).resolve(),
    }
    if destination in reserved_helpers:
        raise ValueError(
            "UVM auto-instrumentation adapter output must be distinct from "
            "the sequence/item marker helper paths"
        )

    if destination.exists() and not force:
        raise FileExistsError(
            f"{destination} already exists; pass --force to replace it"
        )

    sequence_path, sequence_created = _ensure_helper(
        project,
        relative_path=DEFAULT_UVM_SEQUENCE_HELPER,
        writer=write_uvm_sequence_instrumentation,
        required_tokens=(
            "package zddv_uvm_sequence_trace_pkg;",
            "task automatic zddv_uvm_sequence_emit",
        ),
    )
    item_path, item_created = _ensure_helper(
        project,
        relative_path=DEFAULT_UVM_ITEM_HELPER,
        writer=write_uvm_item_instrumentation,
        required_tokens=(
            "package zddv_uvm_item_trace_pkg;",
            "task automatic zddv_uvm_item_emit",
        ),
    )

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(_SV_PACKAGE, encoding="utf-8")

    added_to_project = False
    source_order: list[str] = []
    if add_source:
        assert project_path is not None
        required = [
            DEFAULT_UVM_SEQUENCE_HELPER,
            DEFAULT_UVM_ITEM_HELPER,
            project_path,
        ]
        original = list(project.tb)
        project.tb = required + [
            entry for entry in project.tb if entry not in set(required)
        ]
        added_to_project = project.tb != original
        if added_to_project:
            save_project(project)
        source_order = required

    return {
        "path": str(destination),
        "project_path": project_path,
        "added_to_project": added_to_project,
        "sequence_helper": str(sequence_path),
        "item_helper": str(item_path),
        "sequence_helper_created": sequence_created,
        "item_helper_created": item_created,
        "source_order": source_order,
        "adapter_class": "zddv_instrumented_sequence",
        "automatic_events": [
            "UVM_CREATED",
            "UVM_PRE_START",
            "UVM_PRE_BODY",
            "UVM_BODY",
            "UVM_ENDED",
            "UVM_POST_BODY",
            "UVM_POST_START",
            "UVM_STOPPED",
            "UVM_FINISHED",
            "ARB_REQUEST",
            "GRANT",
            "REQUEST",
            "ITEM_DONE",
            "RESPONSE",
        ],
        "limitations": [
            "A user sequence must explicitly derive from zddv_instrumented_sequence.",
            "Derived sequences implement zddv_body(); overriding body() bypasses the BODY/ENDED wrapper.",
            "Overriding start/pre_start/pre_body/post_body/post_start without calling super bypasses the corresponding adapter markers.",
            "Automatic item markers cover inherited start_item/finish_item/get_response calls.",
            "Direct wait_for_grant/send_request flows and response_handler callbacks require explicit instrumentation.",
            "No hidden sequencer queues, arbitration policy, lock/grab state, or vendor transcript semantics are inferred.",
        ],
    }
