from __future__ import annotations

from pathlib import Path
from typing import Any

from zddv.config import ProjectConfig, save_project


DEFAULT_UVM_SEQUENCE_HELPER = "tb/zddv_uvm_sequence_trace_pkg.sv"
UVM_SEQUENCE_MARKER = "ZDDV_UVM_SEQUENCE"

_SV_PACKAGE = r'''// Generated by ZDDV. Portable, opt-in UVM sequence lifecycle trace helper.
//
// This helper has no dependency on uvm_pkg. Call these tasks from explicit
// UVM sequence lifecycle points owned by the verification environment. The
// emitted marker is consumed by "zddv uvm-sequence-log-analyze".
package zddv_uvm_sequence_trace_pkg;

  function automatic string zddv_json_escape(input string value);
    string result;
    byte unsigned ch;
    result = "";
    for (int i = 0; i < value.len(); i++) begin
      ch = value.getc(i);
      case (ch)
        8'h22: result = {result, "\\\""};
        8'h5c: result = {result, "\\\\"};
        8'h08: result = {result, "\\b"};
        8'h0c: result = {result, "\\f"};
        8'h0a: result = {result, "\\n"};
        8'h0d: result = {result, "\\r"};
        8'h09: result = {result, "\\t"};
        default: begin
          if (ch < 8'h20)
            result = {result, $sformatf("\\u%04x", ch)};
          else
            result = {result, $sformatf("%c", ch)};
        end
      endcase
    end
    return result;
  endfunction

  function automatic string zddv_json_string_or_null(input string value);
    if (value.len() == 0)
      return "null";
    return {"\"", zddv_json_escape(value), "\""};
  endfunction

  task automatic zddv_uvm_sequence_emit(
    input string state_name,
    input string sequence_id,
    input string sequence_name,
    input string sequencer_name = "",
    input string parent_sequence_id = ""
  );
    if ((state_name.len() == 0) || (sequence_id.len() == 0) || (sequence_name.len() == 0)) begin
      $error("ZDDV UVM sequence trace requires non-empty state_name, sequence_id, and sequence_name");
    end
    else begin
      $display(
        "ZDDV_UVM_SEQUENCE {\\\"sequence_id\\\":\\\"%s\\\",\\\"sequence\\\":\\\"%s\\\",\\\"sequencer\\\":%s,\\\"parent_sequence_id\\\":%s,\\\"state\\\":\\\"%s\\\",\\\"time\\\":\\\"%0t\\\",\\\"metadata\\\":{\\\"instrumentation\\\":\\\"zddv_uvm_sequence_trace_pkg\\\"}}",
        zddv_json_escape(sequence_id),
        zddv_json_escape(sequence_name),
        zddv_json_string_or_null(sequencer_name),
        zddv_json_string_or_null(parent_sequence_id),
        zddv_json_escape(state_name),
        $time
      );
    end
  endtask

  task automatic zddv_uvm_sequence_created(
    input string sequence_id,
    input string sequence_name,
    input string sequencer_name = "",
    input string parent_sequence_id = ""
  );
    zddv_uvm_sequence_emit(
      "UVM_CREATED", sequence_id, sequence_name, sequencer_name, parent_sequence_id
    );
  endtask

  task automatic zddv_uvm_sequence_pre_start(
    input string sequence_id,
    input string sequence_name,
    input string sequencer_name = "",
    input string parent_sequence_id = ""
  );
    zddv_uvm_sequence_emit(
      "UVM_PRE_START", sequence_id, sequence_name, sequencer_name, parent_sequence_id
    );
  endtask

  task automatic zddv_uvm_sequence_pre_body(
    input string sequence_id,
    input string sequence_name,
    input string sequencer_name = "",
    input string parent_sequence_id = ""
  );
    zddv_uvm_sequence_emit(
      "UVM_PRE_BODY", sequence_id, sequence_name, sequencer_name, parent_sequence_id
    );
  endtask

  task automatic zddv_uvm_sequence_body(
    input string sequence_id,
    input string sequence_name,
    input string sequencer_name = "",
    input string parent_sequence_id = ""
  );
    zddv_uvm_sequence_emit(
      "UVM_BODY", sequence_id, sequence_name, sequencer_name, parent_sequence_id
    );
  endtask

  task automatic zddv_uvm_sequence_ended(
    input string sequence_id,
    input string sequence_name,
    input string sequencer_name = "",
    input string parent_sequence_id = ""
  );
    zddv_uvm_sequence_emit(
      "UVM_ENDED", sequence_id, sequence_name, sequencer_name, parent_sequence_id
    );
  endtask

  task automatic zddv_uvm_sequence_post_body(
    input string sequence_id,
    input string sequence_name,
    input string sequencer_name = "",
    input string parent_sequence_id = ""
  );
    zddv_uvm_sequence_emit(
      "UVM_POST_BODY", sequence_id, sequence_name, sequencer_name, parent_sequence_id
    );
  endtask

  task automatic zddv_uvm_sequence_post_start(
    input string sequence_id,
    input string sequence_name,
    input string sequencer_name = "",
    input string parent_sequence_id = ""
  );
    zddv_uvm_sequence_emit(
      "UVM_POST_START", sequence_id, sequence_name, sequencer_name, parent_sequence_id
    );
  endtask

  task automatic zddv_uvm_sequence_stopped(
    input string sequence_id,
    input string sequence_name,
    input string sequencer_name = "",
    input string parent_sequence_id = ""
  );
    zddv_uvm_sequence_emit(
      "UVM_STOPPED", sequence_id, sequence_name, sequencer_name, parent_sequence_id
    );
  endtask

  task automatic zddv_uvm_sequence_finished(
    input string sequence_id,
    input string sequence_name,
    input string sequencer_name = "",
    input string parent_sequence_id = ""
  );
    zddv_uvm_sequence_emit(
      "UVM_FINISHED", sequence_id, sequence_name, sequencer_name, parent_sequence_id
    );
  endtask

endpackage
'''


def write_uvm_sequence_instrumentation(
    project: ProjectConfig,
    *,
    output: str | Path = DEFAULT_UVM_SEQUENCE_HELPER,
    add_source: bool = True,
    force: bool = False,
) -> dict[str, Any]:
    destination = Path(output)
    if not destination.is_absolute():
        destination = project.root / destination
    destination = destination.resolve()

    project_path: str | None = None
    if add_source:
        try:
            project_path = destination.relative_to(project.root.resolve()).as_posix()
        except ValueError as exc:
            raise ValueError(
                "Instrumentation helper must be inside the project when source "
                "registration is enabled"
            ) from exc

    if destination.exists() and not force:
        raise FileExistsError(
            f"{destination} already exists; pass --force to replace it"
        )

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(_SV_PACKAGE, encoding="utf-8")

    added_to_project = False
    if add_source:
        assert project_path is not None
        if project_path not in project.tb:
            project.tb.insert(0, project_path)
            save_project(project)
            added_to_project = True

    return {
        "path": str(destination),
        "project_path": project_path,
        "added_to_project": added_to_project,
        "marker": UVM_SEQUENCE_MARKER,
    }
