from __future__ import annotations

from pathlib import Path
from typing import Any

from zddv.config import ProjectConfig, save_project


DEFAULT_UVM_ITEM_HELPER = "tb/zddv_uvm_item_trace_pkg.sv"
UVM_ITEM_MARKER = "ZDDV_UVM_ITEM"

_SV_PACKAGE = r'''// Generated by ZDDV. Portable, opt-in UVM sequence-item trace helper.
//
// This helper has no dependency on the UVM package. Call the tasks below from
// explicit UVM semantic points owned by the verification environment. The
// emitted JSON marker is consumed by "zddv uvm-item-log-analyze".
package zddv_uvm_item_trace_pkg;

  function automatic string zddv_json_escape(input string value);
    string result;
    byte unsigned ch;
    result = "";
    for (int i = 0; i < value.len(); i++) begin
      ch = value.getc(i);
      case (ch)
        8'h22: result = {result, "\\\""};
        8'h5c: result = {result, "\\\\"};
        8'h08: result = {result, "\\b"};
        8'h0c: result = {result, "\\f"};
        8'h0a: result = {result, "\\n"};
        8'h0d: result = {result, "\\r"};
        8'h09: result = {result, "\\t"};
        default: begin
          if (ch < 8'h20)
            result = {result, $sformatf("\\u%04x", ch)};
          else
            result = {result, $sformatf("%c", ch)};
        end
      endcase
    end
    return result;
  endfunction

  function automatic string zddv_json_string_or_null(input string value);
    if (value.len() == 0)
      return "null";
    return {"\"", zddv_json_escape(value), "\""};
  endfunction

  task automatic zddv_uvm_item_emit(
    input string event_name,
    input string item_id,
    input string sequence_id = "",
    input string sequence_name = "",
    input string sequencer_name = "",
    input string item_name = "",
    input longint transaction_id = -1
  );
    string transaction_json;

    if ((event_name.len() == 0) || (item_id.len() == 0)) begin
      $error("ZDDV UVM item trace requires non-empty event_name and item_id");
    end
    else begin
      if (transaction_id < 0)
        transaction_json = "null";
      else
        transaction_json = $sformatf("%0d", transaction_id);

      $display(
        "ZDDV_UVM_ITEM {\"item_id\":\"%s\",\"event\":\"%s\",\"sequence_id\":%s,\"sequence\":%s,\"sequencer\":%s,\"item\":%s,\"transaction_id\":%s,\"time\":\"%0t\",\"metadata\":{\"instrumentation\":\"zddv_uvm_item_trace_pkg\"}}",
        zddv_json_escape(item_id),
        zddv_json_escape(event_name),
        zddv_json_string_or_null(sequence_id),
        zddv_json_string_or_null(sequence_name),
        zddv_json_string_or_null(sequencer_name),
        zddv_json_string_or_null(item_name),
        transaction_json,
        $time
      );
    end
  endtask

  task automatic zddv_uvm_item_arb_request(
    input string item_id,
    input string sequence_id = "",
    input string sequence_name = "",
    input string sequencer_name = "",
    input string item_name = "",
    input longint transaction_id = -1
  );
    zddv_uvm_item_emit(
      "ARB_REQUEST", item_id, sequence_id, sequence_name,
      sequencer_name, item_name, transaction_id
    );
  endtask

  task automatic zddv_uvm_item_grant(
    input string item_id,
    input string sequence_id = "",
    input string sequence_name = "",
    input string sequencer_name = "",
    input string item_name = "",
    input longint transaction_id = -1
  );
    zddv_uvm_item_emit(
      "GRANT", item_id, sequence_id, sequence_name,
      sequencer_name, item_name, transaction_id
    );
  endtask

  task automatic zddv_uvm_item_request(
    input string item_id,
    input string sequence_id = "",
    input string sequence_name = "",
    input string sequencer_name = "",
    input string item_name = "",
    input longint transaction_id = -1
  );
    zddv_uvm_item_emit(
      "REQUEST", item_id, sequence_id, sequence_name,
      sequencer_name, item_name, transaction_id
    );
  endtask

  task automatic zddv_uvm_item_done(
    input string item_id,
    input string sequence_id = "",
    input string sequence_name = "",
    input string sequencer_name = "",
    input string item_name = "",
    input longint transaction_id = -1
  );
    zddv_uvm_item_emit(
      "ITEM_DONE", item_id, sequence_id, sequence_name,
      sequencer_name, item_name, transaction_id
    );
  endtask

  task automatic zddv_uvm_item_response(
    input string item_id,
    input string sequence_id = "",
    input string sequence_name = "",
    input string sequencer_name = "",
    input string item_name = "",
    input longint transaction_id = -1
  );
    zddv_uvm_item_emit(
      "RESPONSE", item_id, sequence_id, sequence_name,
      sequencer_name, item_name, transaction_id
    );
  endtask

endpackage
'''


def write_uvm_item_instrumentation(
    project: ProjectConfig,
    *,
    output: str | Path = DEFAULT_UVM_ITEM_HELPER,
    add_source: bool = True,
    force: bool = False,
) -> dict[str, Any]:
    destination = Path(output)
    if not destination.is_absolute():
        destination = project.root / destination
    destination = destination.resolve()

    if destination.exists() and not force:
        raise FileExistsError(
            f"{destination} already exists; pass --force to replace it"
        )

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(_SV_PACKAGE, encoding="utf-8")

    project_path: str | None = None
    added_to_project = False
    if add_source:
        try:
            project_path = destination.relative_to(project.root.resolve()).as_posix()
        except ValueError as exc:
            raise ValueError(
                "Instrumentation helper must be inside the project when source "
                "registration is enabled"
            ) from exc

        if project_path not in project.tb:
            project.tb.insert(0, project_path)
            save_project(project)
            added_to_project = True

    return {
        "path": str(destination),
        "project_path": project_path,
        "added_to_project": added_to_project,
        "marker": UVM_ITEM_MARKER,
    }
